spring.application.name=confeitariaMacedoFarias

spring.datasource.url=jdbc:h2:mem:confeitaria
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:TEST-1534102487843116-031120-434a49e7daa7e1fb36768d61c3e0be47-1322028982}

admin.password=${ADMIN_PASSWORD:securePassword123}

# WhatsApp
whatsapp.api.url=${WHATSAPP_API_URL:https://api.z-api.io/instances/YOUR_INSTANCE/send-text}
whatsapp.api.token=${WHATSAPP_API_TOKEN:YOUR_TOKEN}
whatsapp.phone.number=${WHATSAPP_PHONE_NUMBER:5521990757721}

# Taxa de entrega fixa em reais
delivery.fee=6.0
