spring.application.name=confeitariaMacedoFarias

spring.datasource.url=jdbc:postgresql://ep-raspy-feather-amh6vw3s-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SKZzA7RcmU9v

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:TEST-1534102487843116-031120-434a49e7daa7e1fb36768d61c3e0be47-1322028982}

admin.password=${ADMIN_PASSWORD:securePassword123}

# WhatsApp
whatsapp.api.url=${WHATSAPP_API_URL:https://api.z-api.io/instances/YOUR_INSTANCE/send-text}
whatsapp.api.token=${WHATSAPP_API_TOKEN:YOUR_TOKEN}
whatsapp.phone.number=${WHATSAPP_PHONE_NUMBER:5521990757721}

# Taxa de entrega fixa em reais
delivery.fee=6.0
