spring.application.name=confeitariaMacedoFarias

server.port=8080

spring.datasource.url=jdbc:postgresql://ep-raspy-feather-amh6vw3s-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SKZzA7RcmU9v

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mercadopago.access.token=seu_token_aqui

admin.email=admin@confeitaria.local
admin.password=changeMe123

mercadopago.webhook.secret=seu_webhook_secret_aqui

whatsapp.api.url=
whatsapp.api.token=
whatsapp.phone.number=

jwt.secret=change-me-please-change-me-please-change
jwt.expiration-ms=86400000

delivery.fee=6.0
