spring.application.name=confeitariaMacedoFarias

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

mercadopago.webhook.secret=${MERCADOPAGO_WEBHOOK_SECRET}

whatsapp.api.url=${WHATSAPP_API_URL}
whatsapp.api.token=${WHATSAPP_API_TOKEN}
whatsapp.phone.number=${WHATSAPP_PHONE_NUMBER}

delivery.fee=6.0
